"""edit user and film model and unique constraind

Revision ID: 2830ea42c5be
Revises: ae7344be0cde
Create Date: 2025-10-30 03:09:09.119437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2830ea42c5be'
down_revision: Union[str, Sequence[str], None] = 'ae7344be0cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_film_country', 'film_country', ['film_id', 'country_id'])
    op.create_unique_constraint('uq_film_genre', 'film_genre', ['film_id', 'genre_id'])
    op.create_unique_constraint('uq_film_still', 'film_still', ['film_id', 'picture_id', 'source'])
    op.create_unique_constraint('uq_film_stuff', 'film_stuff', ['film_id', 'stuff_id', 'role'])
    op.create_unique_constraint('uq_film_watch_provider', 'film_watch_provider', ['film_id', 'name'])
    op.create_unique_constraint('uq_similar_film', 'similar_film', ['film_id', 'similar_film_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_similar_film', 'similar_film', type_='unique')
    op.drop_constraint('uq_film_watch_provider', 'film_watch_provider', type_='unique')
    op.drop_constraint('uq_film_stuff', 'film_stuff', type_='unique')
    op.drop_constraint('uq_film_still', 'film_still', type_='unique')
    op.drop_constraint('uq_film_genre', 'film_genre', type_='unique')
    op.drop_constraint('uq_film_country', 'film_country', type_='unique')
    # ### end Alembic commands ###
