"""edit index

Revision ID: c35037a3d2fc
Revises: 5967d27b197f
Create Date: 2025-11-20 02:29:54.955198

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c35037a3d2fc"
down_revision: Union[str, Sequence[str], None] = "5967d27b197f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_film_rating_imdb"), "film", ["rating_imdb"], unique=False
    )
    op.create_index(
        op.f("ix_film_rating_kp"), "film", ["rating_kp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_film_rating_kp"), table_name="film")
    op.drop_index(op.f("ix_film_rating_imdb"), table_name="film")
    # ### end Alembic commands ###
