"""create access_tokens table

Revision ID: 6493ca02052d
Revises: e7358ebf462c
Create Date: 2025-10-18 21:44:33.146142

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '6493ca02052d'
down_revision: Union[str, Sequence[str], None] = 'e7358ebf462c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
