"""update backend api

Revision ID: 13d277130949
Revises: c35037a3d2fc
Create Date: 2026-01-10 19:10:57.994947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13d277130949'
down_revision: Union[str, Sequence[str], None] = 'c35037a3d2fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_images',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('picture_id', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_images')),
    sa.UniqueConstraint('content_id', 'content_type', 'picture_id', 'image_type', name='uq_content_image')
    )
    op.create_table('content_watch_provider',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=False),
    sa.Column('provider_url', sa.Text(), nullable=False),
    sa.Column('provider_logo', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_watch_provider')),
    sa.UniqueConstraint('content_id', 'content_type', 'provider_name', name='uq_content_watch_provider')
    )
    op.create_table('series',
    sa.Column('kinopoisk_id', sa.String(length=20), nullable=False),
    sa.Column('title_ru', sa.String(length=500), nullable=True),
    sa.Column('title_en', sa.String(length=500), nullable=True),
    sa.Column('description_short', sa.Text(), nullable=True),
    sa.Column('description_full', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.String(length=1000), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('premiere_ru', sa.String(length=100), nullable=True),
    sa.Column('premiere_world', sa.String(length=100), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('is_family', sa.Boolean(), nullable=False),
    sa.Column('rating_kp', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('votes_kp', sa.Integer(), nullable=True),
    sa.Column('rating_imdb', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('votes_imdb', sa.Integer(), nullable=True),
    sa.Column('rating_user', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('votes_user', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=200), nullable=True),
    sa.Column('episodes_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series'))
    )
    op.create_index(op.f('ix_series_kinopoisk_id'), 'series', ['kinopoisk_id'], unique=True)
    op.create_index(op.f('ix_series_rating_imdb'), 'series', ['rating_imdb'], unique=False)
    op.create_index(op.f('ix_series_rating_kp'), 'series', ['rating_kp'], unique=False)
    op.create_index(op.f('ix_series_release_year'), 'series', ['release_year'], unique=False)
    op.create_index(op.f('ix_series_title_en'), 'series', ['title_en'], unique=False)
    op.create_index(op.f('ix_series_title_ru'), 'series', ['title_ru'], unique=False)
    op.create_table('similar_content',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('similar_id', sa.String(length=20), nullable=False),
    sa.Column('similar_type', sa.String(length=20), nullable=False),
    sa.Column('title_ru', sa.String(length=500), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('poster_url', sa.Text(), nullable=True),
    sa.Column('rating_kp', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_similar_content')),
    sa.UniqueConstraint('content_id', 'content_type', 'similar_id', 'similar_type', name='uq_similar_content')
    )
    op.create_table('content_country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name=op.f('fk_content_country_country_id_country'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_country')),
    sa.UniqueConstraint('content_id', 'content_type', 'country_id', name='uq_content_country')
    )
    op.create_table('content_genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name=op.f('fk_content_genre_genre_id_genre'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_genre')),
    sa.UniqueConstraint('content_id', 'content_type', 'genre_id', name='uq_content_genre')
    )
    op.create_table('content_stuff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('stuff_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['stuff_id'], ['stuff.id'], name=op.f('fk_content_stuff_stuff_id_stuff'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_stuff')),
    sa.UniqueConstraint('content_id', 'content_type', 'stuff_id', 'role', name='uq_content_stuff')
    )
    op.create_table('stuff_filmography',
    sa.Column('stuff_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.String(length=20), nullable=False),
    sa.Column('title_ru', sa.String(length=500), nullable=True),
    sa.Column('title_en', sa.String(length=500), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('countries', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.String(length=1000), nullable=True),
    sa.Column('rating_kp', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('votes_kp', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('release_year_start', sa.Integer(), nullable=True),
    sa.Column('release_year_end', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stuff_id'], ['stuff.id'], name=op.f('fk_stuff_filmography_stuff_id_stuff'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stuff_filmography')),
    sa.UniqueConstraint('stuff_id', 'content_id', 'role', name='uq_stuff_filmography')
    )
    op.create_table('stuff_images',
    sa.Column('stuff_id', sa.Integer(), nullable=False),
    sa.Column('picture_id', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stuff_id'], ['stuff.id'], name=op.f('fk_stuff_images_stuff_id_stuff'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stuff_images')),
    sa.UniqueConstraint('stuff_id', 'picture_id', 'image_type', name='uq_stuff_image')
    )
    op.create_table('user_ratings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_ratings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_ratings')),
    sa.UniqueConstraint('user_id', 'content_id', 'content_type', name='uq_rating_user_content')
    )
    op.drop_table('film_genre')
    op.drop_table('similar_film')
    op.drop_table('film_watch_provider')
    op.drop_table('film_country')
    op.drop_table('film_stuff')
    op.drop_table('film_still')
    op.drop_table('user_film_ratings')
    op.add_column('bookmarks', sa.Column('content_id', sa.Integer(), nullable=False))
    op.add_column('bookmarks', sa.Column('content_type', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('uq_bookmark_user_film'), 'bookmarks', type_='unique')
    op.create_unique_constraint('uq_bookmark_user_content', 'bookmarks', ['user_id', 'content_id', 'content_type'])
    op.drop_constraint(op.f('fk_bookmarks_film_id_film'), 'bookmarks', type_='foreignkey')
    op.drop_column('bookmarks', 'film_id')
    op.add_column('comments', sa.Column('content_id', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('content_type', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('fk_comments_film_id_film'), 'comments', type_='foreignkey')
    op.drop_column('comments', 'film_id')
    op.add_column('film', sa.Column('title_ru', sa.String(length=500), nullable=True))
    op.add_column('film', sa.Column('title_en', sa.String(length=500), nullable=True))
    op.add_column('film', sa.Column('description_short', sa.Text(), nullable=True))
    op.add_column('film', sa.Column('description_full', sa.Text(), nullable=True))
    op.add_column('film', sa.Column('poster_url', sa.String(length=1000), nullable=True))
    op.add_column('film', sa.Column('release_year', sa.Integer(), nullable=True))
    op.add_column('film', sa.Column('premiere_ru', sa.String(length=100), nullable=True))
    op.add_column('film', sa.Column('premiere_world', sa.String(length=100), nullable=True))
    op.add_column('film', sa.Column('content_type', sa.String(length=50), nullable=False))
    op.add_column('film', sa.Column('is_family', sa.Boolean(), nullable=False))
    op.add_column('film', sa.Column('votes_kp', sa.Integer(), nullable=True))
    op.add_column('film', sa.Column('votes_imdb', sa.Integer(), nullable=True))
    op.add_column('film', sa.Column('rating_user', sa.DECIMAL(precision=3, scale=1), nullable=True))
    op.add_column('film', sa.Column('votes_user', sa.Integer(), nullable=False))
    op.add_column('film', sa.Column('box_office_usa', sa.String(length=100), nullable=True))
    op.add_column('film', sa.Column('box_office_rus', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_film_original_title'), table_name='film')
    op.drop_index(op.f('ix_film_title'), table_name='film')
    op.drop_index(op.f('ix_film_year'), table_name='film')
    op.create_index(op.f('ix_film_release_year'), 'film', ['release_year'], unique=False)
    op.create_index(op.f('ix_film_title_en'), 'film', ['title_en'], unique=False)
    op.create_index(op.f('ix_film_title_ru'), 'film', ['title_ru'], unique=False)
    op.drop_column('film', 'title')
    op.drop_column('film', 'content_rating')
    op.drop_column('film', 'year')
    op.drop_column('film', 'ru_premiere')
    op.drop_column('film', 'user_rating')
    op.drop_column('film', 'kp_votes_count')
    op.drop_column('film', 'is_family_friendly')
    op.drop_column('film', 'rus_box_office')
    op.drop_column('film', 'imdb_votes_count')
    op.drop_column('film', 'poster')
    op.drop_column('film', 'full_description')
    op.drop_column('film', 'world_premiere')
    op.drop_column('film', 'usa_box_office')
    op.drop_column('film', 'original_title')
    op.drop_column('film', 'user_rating_count')
    op.drop_column('film', 'description')
    op.add_column('media', sa.Column('image_url', sa.String(length=1000), nullable=True))
    op.add_column('media', sa.Column('publish_date', sa.String(length=100), nullable=True))
    op.drop_column('media', 'image')
    op.drop_column('media', 'date')
    op.add_column('stuff', sa.Column('name_ru', sa.String(length=200), nullable=True))
    op.add_column('stuff', sa.Column('name_en', sa.String(length=200), nullable=True))
    op.add_column('stuff', sa.Column('genres', sa.ARRAY(sa.Text()), nullable=True))
    op.add_column('stuff', sa.Column('birth_date', sa.String(length=100), nullable=True))
    op.add_column('stuff', sa.Column('birth_place', sa.ARRAY(sa.Text()), nullable=True))
    op.add_column('stuff', sa.Column('films_total', sa.Integer(), nullable=True))
    op.add_column('stuff', sa.Column('career_start', sa.Integer(), nullable=True))
    op.add_column('stuff', sa.Column('photo_url', sa.String(length=1000), nullable=True))
    op.drop_index(op.f('ix_stuff_name'), table_name='stuff')
    op.drop_index(op.f('ix_stuff_original_name'), table_name='stuff')
    op.create_index(op.f('ix_stuff_name_en'), 'stuff', ['name_en'], unique=False)
    op.create_index(op.f('ix_stuff_name_ru'), 'stuff', ['name_ru'], unique=False)
    op.drop_column('stuff', 'birthday_day_month')
    op.drop_column('stuff', 'career_start_year')
    op.drop_column('stuff', 'image')
    op.drop_column('stuff', 'career_end_year')
    op.drop_column('stuff', 'ganres')
    op.drop_column('stuff', 'name')
    op.drop_column('stuff', 'age')
    op.drop_column('stuff', 'birthplace')
    op.drop_column('stuff', 'original_name')
    op.drop_column('stuff', 'total_films')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stuff', sa.Column('total_films', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stuff', sa.Column('original_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('stuff', sa.Column('birthplace', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('stuff', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stuff', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('stuff', sa.Column('ganres', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('stuff', sa.Column('career_end_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stuff', sa.Column('image', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('stuff', sa.Column('career_start_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stuff', sa.Column('birthday_day_month', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_stuff_name_ru'), table_name='stuff')
    op.drop_index(op.f('ix_stuff_name_en'), table_name='stuff')
    op.create_index(op.f('ix_stuff_original_name'), 'stuff', ['original_name'], unique=False)
    op.create_index(op.f('ix_stuff_name'), 'stuff', ['name'], unique=False)
    op.drop_column('stuff', 'photo_url')
    op.drop_column('stuff', 'career_start')
    op.drop_column('stuff', 'films_total')
    op.drop_column('stuff', 'birth_place')
    op.drop_column('stuff', 'birth_date')
    op.drop_column('stuff', 'genres')
    op.drop_column('stuff', 'name_en')
    op.drop_column('stuff', 'name_ru')
    op.add_column('media', sa.Column('date', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('media', sa.Column('image', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('media', 'publish_date')
    op.drop_column('media', 'image_url')
    op.add_column('film', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('film', sa.Column('user_rating_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('film', sa.Column('original_title', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('film', sa.Column('usa_box_office', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('film', sa.Column('world_premiere', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('film', sa.Column('full_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('film', sa.Column('poster', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('film', sa.Column('imdb_votes_count', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('film', sa.Column('rus_box_office', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('film', sa.Column('is_family_friendly', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('film', sa.Column('kp_votes_count', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('film', sa.Column('user_rating', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True))
    op.add_column('film', sa.Column('ru_premiere', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('film', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('film', sa.Column('content_rating', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('film', sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_film_title_ru'), table_name='film')
    op.drop_index(op.f('ix_film_title_en'), table_name='film')
    op.drop_index(op.f('ix_film_release_year'), table_name='film')
    op.create_index(op.f('ix_film_year'), 'film', ['year'], unique=False)
    op.create_index(op.f('ix_film_title'), 'film', ['title'], unique=False)
    op.create_index(op.f('ix_film_original_title'), 'film', ['original_title'], unique=False)
    op.drop_column('film', 'box_office_rus')
    op.drop_column('film', 'box_office_usa')
    op.drop_column('film', 'votes_user')
    op.drop_column('film', 'rating_user')
    op.drop_column('film', 'votes_imdb')
    op.drop_column('film', 'votes_kp')
    op.drop_column('film', 'is_family')
    op.drop_column('film', 'content_type')
    op.drop_column('film', 'premiere_world')
    op.drop_column('film', 'premiere_ru')
    op.drop_column('film', 'release_year')
    op.drop_column('film', 'poster_url')
    op.drop_column('film', 'description_full')
    op.drop_column('film', 'description_short')
    op.drop_column('film', 'title_en')
    op.drop_column('film', 'title_ru')
    op.add_column('comments', sa.Column('film_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_comments_film_id_film'), 'comments', 'film', ['film_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'content_type')
    op.drop_column('comments', 'content_id')
    op.add_column('bookmarks', sa.Column('film_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_bookmarks_film_id_film'), 'bookmarks', 'film', ['film_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_bookmark_user_content', 'bookmarks', type_='unique')
    op.create_unique_constraint(op.f('uq_bookmark_user_film'), 'bookmarks', ['user_id', 'film_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('bookmarks', 'content_type')
    op.drop_column('bookmarks', 'content_id')
    op.create_table('user_film_ratings',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('film_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], name=op.f('fk_user_film_ratings_film_id_film'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_film_ratings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_film_ratings')),
    sa.UniqueConstraint('user_id', 'film_id', name=op.f('uq_rating_user_film'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('film_still',
    sa.Column('film_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('picture_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('original_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], name=op.f('fk_film_still_film_id_film'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_film_still')),
    sa.UniqueConstraint('film_id', 'picture_id', 'source', name=op.f('uq_film_still'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('film_stuff',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stuff_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], name=op.f('fk_film_stuff_film_id_film'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stuff_id'], ['stuff.id'], name=op.f('fk_film_stuff_stuff_id_stuff'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_film_stuff')),
    sa.UniqueConstraint('film_id', 'stuff_id', 'role', name=op.f('uq_film_stuff'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('film_country',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name=op.f('fk_film_country_country_id_country'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], name=op.f('fk_film_country_film_id_film'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_film_country')),
    sa.UniqueConstraint('film_id', 'country_id', name=op.f('uq_film_country'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('film_watch_provider',
    sa.Column('film_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('logo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], name=op.f('fk_film_watch_provider_film_id_film'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_film_watch_provider')),
    sa.UniqueConstraint('film_id', 'name', name=op.f('uq_film_watch_provider'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('similar_film',
    sa.Column('film_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('similar_film_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('similar_film_title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('similar_film_year', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('similar_film_genres', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('similar_film_poster', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('similar_film_rating', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], name=op.f('fk_similar_film_film_id_film'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_similar_film')),
    sa.UniqueConstraint('film_id', 'similar_film_id', name=op.f('uq_similar_film'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('film_genre',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], name=op.f('fk_film_genre_film_id_film'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name=op.f('fk_film_genre_genre_id_genre'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_film_genre')),
    sa.UniqueConstraint('film_id', 'genre_id', name=op.f('uq_film_genre'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('user_ratings')
    op.drop_table('stuff_images')
    op.drop_table('stuff_filmography')
    op.drop_table('content_stuff')
    op.drop_table('content_genre')
    op.drop_table('content_country')
    op.drop_table('similar_content')
    op.drop_index(op.f('ix_series_title_ru'), table_name='series')
    op.drop_index(op.f('ix_series_title_en'), table_name='series')
    op.drop_index(op.f('ix_series_release_year'), table_name='series')
    op.drop_index(op.f('ix_series_rating_kp'), table_name='series')
    op.drop_index(op.f('ix_series_rating_imdb'), table_name='series')
    op.drop_index(op.f('ix_series_kinopoisk_id'), table_name='series')
    op.drop_table('series')
    op.drop_table('content_watch_provider')
    op.drop_table('content_images')
    # ### end Alembic commands ###
