"""update user rating table

Revision ID: 794d8f2a1dae
Revises: 13d277130949
Create Date: 2026-01-13 22:13:36.180378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '794d8f2a1dae'
down_revision: Union[str, Sequence[str], None] = '13d277130949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_user_rating',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('rating_user', sa.Float(), nullable=False),
    sa.Column('votes_user', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_user_rating')),
    sa.UniqueConstraint('content_id', 'content_type', name='uq_content_user_rating')
    )
    op.drop_column('film', 'votes_user')
    op.drop_column('film', 'rating_user')
    op.drop_column('series', 'votes_user')
    op.drop_column('series', 'rating_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('rating_user', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True))
    op.add_column('series', sa.Column('votes_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('film', sa.Column('rating_user', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True))
    op.add_column('film', sa.Column('votes_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('content_user_rating')
    # ### end Alembic commands ###
