"""delete media model

Revision ID: f7bc4a0bdc75
Revises: c35037a3d2fc
Create Date: 2026-01-15 16:45:33.091839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7bc4a0bdc75'
down_revision: Union[str, Sequence[str], None] = 'c35037a3d2fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_category'), table_name='media')
    op.drop_index(op.f('ix_media_title'), table_name='media')
    op.drop_index(op.f('ix_media_type'), table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('card_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('parsed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media')),
    sa.UniqueConstraint('url', name=op.f('uq_media_url'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_media_type'), 'media', ['type'], unique=False)
    op.create_index(op.f('ix_media_title'), 'media', ['title'], unique=False)
    op.create_index(op.f('ix_media_category'), 'media', ['category'], unique=False)
    # ### end Alembic commands ###
