"""add all models

Revision ID: ae7344be0cde
Revises: 43caba6e9882
Create Date: 2025-10-25 19:20:08.867391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7344be0cde'
down_revision: Union[str, Sequence[str], None] = '43caba6e9882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country'))
    )
    op.create_index(op.f('ix_country_name'), 'country', ['name'], unique=True)
    op.create_table('film',
    sa.Column('kinopoisk_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('full_description', sa.Text(), nullable=True),
    sa.Column('poster', sa.String(length=1000), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('ru_premiere', sa.String(length=100), nullable=True),
    sa.Column('world_premiere', sa.String(length=100), nullable=True),
    sa.Column('content_rating', sa.String(length=20), nullable=True),
    sa.Column('is_family_friendly', sa.Boolean(), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('rating_kp', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('kp_votes_count', sa.String(length=50), nullable=True),
    sa.Column('rating_imdb', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('imdb_votes_count', sa.String(length=50), nullable=True),
    sa.Column('user_rating', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('user_rating_count', sa.Integer(), nullable=False),
    sa.Column('budget', sa.String(length=100), nullable=True),
    sa.Column('usa_box_office', sa.String(length=100), nullable=True),
    sa.Column('rus_box_office', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_film'))
    )
    op.create_index(op.f('ix_film_kinopoisk_id'), 'film', ['kinopoisk_id'], unique=True)
    op.create_index(op.f('ix_film_original_title'), 'film', ['original_title'], unique=False)
    op.create_index(op.f('ix_film_title'), 'film', ['title'], unique=False)
    op.create_index(op.f('ix_film_year'), 'film', ['year'], unique=False)
    op.create_table('genre',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genre'))
    )
    op.create_index(op.f('ix_genre_name'), 'genre', ['name'], unique=True)
    op.create_table('media',
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('image', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('card_type', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media')),
    sa.UniqueConstraint('url', name=op.f('uq_media_url'))
    )
    op.create_index(op.f('ix_media_category'), 'media', ['category'], unique=False)
    op.create_index(op.f('ix_media_title'), 'media', ['title'], unique=False)
    op.create_index(op.f('ix_media_type'), 'media', ['type'], unique=False)
    op.create_table('stuff',
    sa.Column('kinopoisk_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('original_name', sa.String(length=200), nullable=True),
    sa.Column('career', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('ganres', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('height', sa.String(length=50), nullable=True),
    sa.Column('birthday_day_month', sa.String(length=50), nullable=True),
    sa.Column('zodiac', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('birthplace', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('spouse', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('children', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('total_films', sa.Integer(), nullable=True),
    sa.Column('career_start_year', sa.Integer(), nullable=True),
    sa.Column('career_end_year', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stuff'))
    )
    op.create_index(op.f('ix_stuff_kinopoisk_id'), 'stuff', ['kinopoisk_id'], unique=True)
    op.create_index(op.f('ix_stuff_name'), 'stuff', ['name'], unique=False)
    op.create_index(op.f('ix_stuff_original_name'), 'stuff', ['original_name'], unique=False)
    op.create_table('bookmarks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], name=op.f('fk_bookmarks_film_id_film'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookmarks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookmarks')),
    sa.UniqueConstraint('user_id', 'film_id', name='uq_bookmark_user_film')
    )
    op.create_table('comments',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], name=op.f('fk_comments_film_id_film'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_table('film_country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name=op.f('fk_film_country_country_id_country'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], name=op.f('fk_film_country_film_id_film'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_film_country'))
    )
    op.create_table('film_genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], name=op.f('fk_film_genre_film_id_film'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name=op.f('fk_film_genre_genre_id_genre'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_film_genre'))
    )
    op.create_table('film_still',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('picture_id', sa.String(length=20), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], name=op.f('fk_film_still_film_id_film'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_film_still'))
    )
    op.create_table('film_stuff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('stuff_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], name=op.f('fk_film_stuff_film_id_film'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stuff_id'], ['stuff.id'], name=op.f('fk_film_stuff_stuff_id_stuff'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_film_stuff'))
    )
    op.create_table('film_watch_provider',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], name=op.f('fk_film_watch_provider_film_id_film'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_film_watch_provider'))
    )
    op.create_table('similar_film',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('similar_film_id', sa.String(length=20), nullable=False),
    sa.Column('similar_film_title', sa.String(length=500), nullable=False),
    sa.Column('similar_film_year', sa.String(length=10), nullable=True),
    sa.Column('similar_film_genres', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('similar_film_poster', sa.Text(), nullable=True),
    sa.Column('similar_film_rating', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], name=op.f('fk_similar_film_film_id_film'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_similar_film'))
    )
    op.create_table('user_film_history',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('visited_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], name=op.f('fk_user_film_history_film_id_film'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_film_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_film_history')),
    sa.UniqueConstraint('user_id', 'film_id', name='uq_history_user_film')
    )
    op.create_table('user_film_ratings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], name=op.f('fk_user_film_ratings_film_id_film'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_film_ratings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_film_ratings')),
    sa.UniqueConstraint('user_id', 'film_id', name='uq_rating_user_film')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_film_ratings')
    op.drop_table('user_film_history')
    op.drop_table('similar_film')
    op.drop_table('film_watch_provider')
    op.drop_table('film_stuff')
    op.drop_table('film_still')
    op.drop_table('film_genre')
    op.drop_table('film_country')
    op.drop_table('comments')
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_stuff_original_name'), table_name='stuff')
    op.drop_index(op.f('ix_stuff_name'), table_name='stuff')
    op.drop_index(op.f('ix_stuff_kinopoisk_id'), table_name='stuff')
    op.drop_table('stuff')
    op.drop_index(op.f('ix_media_type'), table_name='media')
    op.drop_index(op.f('ix_media_title'), table_name='media')
    op.drop_index(op.f('ix_media_category'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_genre_name'), table_name='genre')
    op.drop_table('genre')
    op.drop_index(op.f('ix_film_year'), table_name='film')
    op.drop_index(op.f('ix_film_title'), table_name='film')
    op.drop_index(op.f('ix_film_original_title'), table_name='film')
    op.drop_index(op.f('ix_film_kinopoisk_id'), table_name='film')
    op.drop_table('film')
    op.drop_index(op.f('ix_country_name'), table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###
