"""add_unique_constraints_to_junction_tables

Revision ID: 7d5bb5329fd9
Revises: ae7344be0cde
Create Date: 2025-10-25 19:51:28.940960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d5bb5329fd9'
down_revision: Union[str, Sequence[str], None] = 'ae7344be0cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_bookmarks_film_id_film'), 'bookmarks', 'film', ['film_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_comments_film_id_film'), 'comments', 'film', ['film_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('country_name_key'), 'country', type_='unique')
    op.create_index(op.f('ix_country_name'), 'country', ['name'], unique=True)
    op.alter_column('film', 'is_family_friendly',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('film', 'user_rating_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('film_kinopoisk_id_key'), 'film', type_='unique')
    op.create_index(op.f('ix_film_kinopoisk_id'), 'film', ['kinopoisk_id'], unique=True)
    op.create_index(op.f('ix_film_original_title'), 'film', ['original_title'], unique=False)
    op.create_index(op.f('ix_film_title'), 'film', ['title'], unique=False)
    op.create_index(op.f('ix_film_year'), 'film', ['year'], unique=False)
    op.drop_constraint(op.f('film_country_film_id_country_id_key'), 'film_country', type_='unique')
    op.create_unique_constraint('uq_film_country', 'film_country', ['film_id', 'country_id'])
    op.drop_constraint(op.f('film_genre_film_id_genre_id_key'), 'film_genre', type_='unique')
    op.create_unique_constraint('uq_film_genre', 'film_genre', ['film_id', 'genre_id'])
    op.drop_constraint(op.f('film_still_film_id_picture_id_source_key'), 'film_still', type_='unique')
    op.create_unique_constraint('uq_film_still', 'film_still', ['film_id', 'picture_id', 'source'])
    op.drop_constraint(op.f('film_stuff_film_id_stuff_id_role_key'), 'film_stuff', type_='unique')
    op.create_unique_constraint('uq_film_stuff', 'film_stuff', ['film_id', 'stuff_id', 'role'])
    op.alter_column('film_watch_provider', 'film_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('film_watch_provider_film_id_name_key'), 'film_watch_provider', type_='unique')
    op.create_unique_constraint('uq_film_watch_provider', 'film_watch_provider', ['film_id', 'name'])
    op.drop_constraint(op.f('genre_name_key'), 'genre', type_='unique')
    op.create_index(op.f('ix_genre_name'), 'genre', ['name'], unique=True)
    op.alter_column('media', 'comments_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('media', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'news'::character varying"))
    op.alter_column('media', 'parsed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('media_url_key'), 'media', type_='unique')
    op.create_index(op.f('ix_media_category'), 'media', ['category'], unique=False)
    op.create_index(op.f('ix_media_title'), 'media', ['title'], unique=False)
    op.create_index(op.f('ix_media_type'), 'media', ['type'], unique=False)
    op.create_unique_constraint(op.f('uq_media_url'), 'media', ['url'])
    op.alter_column('similar_film', 'film_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('similar_film', 'similar_film_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('similar_film', 'similar_film_title',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_constraint(op.f('similar_film_film_id_similar_film_id_key'), 'similar_film', type_='unique')
    op.create_unique_constraint('uq_similar_film', 'similar_film', ['film_id', 'similar_film_id'])
    op.drop_constraint(op.f('stuff_kinopoisk_id_key'), 'stuff', type_='unique')
    op.create_index(op.f('ix_stuff_kinopoisk_id'), 'stuff', ['kinopoisk_id'], unique=True)
    op.create_index(op.f('ix_stuff_name'), 'stuff', ['name'], unique=False)
    op.create_index(op.f('ix_stuff_original_name'), 'stuff', ['original_name'], unique=False)
    op.create_foreign_key(op.f('fk_user_film_history_film_id_film'), 'user_film_history', 'film', ['film_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_user_film_ratings_film_id_film'), 'user_film_ratings', 'film', ['film_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_film_ratings_film_id_film'), 'user_film_ratings', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_film_history_film_id_film'), 'user_film_history', type_='foreignkey')
    op.drop_index(op.f('ix_stuff_original_name'), table_name='stuff')
    op.drop_index(op.f('ix_stuff_name'), table_name='stuff')
    op.drop_index(op.f('ix_stuff_kinopoisk_id'), table_name='stuff')
    op.create_unique_constraint(op.f('stuff_kinopoisk_id_key'), 'stuff', ['kinopoisk_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_similar_film', 'similar_film', type_='unique')
    op.create_unique_constraint(op.f('similar_film_film_id_similar_film_id_key'), 'similar_film', ['film_id', 'similar_film_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('similar_film', 'similar_film_title',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('similar_film', 'similar_film_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('similar_film', 'film_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('uq_media_url'), 'media', type_='unique')
    op.drop_index(op.f('ix_media_type'), table_name='media')
    op.drop_index(op.f('ix_media_title'), table_name='media')
    op.drop_index(op.f('ix_media_category'), table_name='media')
    op.create_unique_constraint(op.f('media_url_key'), 'media', ['url'], postgresql_nulls_not_distinct=False)
    op.alter_column('media', 'parsed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('media', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'news'::character varying"))
    op.alter_column('media', 'comments_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_genre_name'), table_name='genre')
    op.create_unique_constraint(op.f('genre_name_key'), 'genre', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_film_watch_provider', 'film_watch_provider', type_='unique')
    op.create_unique_constraint(op.f('film_watch_provider_film_id_name_key'), 'film_watch_provider', ['film_id', 'name'], postgresql_nulls_not_distinct=False)
    op.alter_column('film_watch_provider', 'film_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_film_stuff', 'film_stuff', type_='unique')
    op.create_unique_constraint(op.f('film_stuff_film_id_stuff_id_role_key'), 'film_stuff', ['film_id', 'stuff_id', 'role'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_film_still', 'film_still', type_='unique')
    op.create_unique_constraint(op.f('film_still_film_id_picture_id_source_key'), 'film_still', ['film_id', 'picture_id', 'source'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_film_genre', 'film_genre', type_='unique')
    op.create_unique_constraint(op.f('film_genre_film_id_genre_id_key'), 'film_genre', ['film_id', 'genre_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_film_country', 'film_country', type_='unique')
    op.create_unique_constraint(op.f('film_country_film_id_country_id_key'), 'film_country', ['film_id', 'country_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_film_year'), table_name='film')
    op.drop_index(op.f('ix_film_title'), table_name='film')
    op.drop_index(op.f('ix_film_original_title'), table_name='film')
    op.drop_index(op.f('ix_film_kinopoisk_id'), table_name='film')
    op.create_unique_constraint(op.f('film_kinopoisk_id_key'), 'film', ['kinopoisk_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('film', 'user_rating_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('film', 'is_family_friendly',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_country_name'), table_name='country')
    op.create_unique_constraint(op.f('country_name_key'), 'country', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('fk_comments_film_id_film'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('fk_bookmarks_film_id_film'), 'bookmarks', type_='foreignkey')
    # ### end Alembic commands ###
