"""update users table

Revision ID: be930e013b3a
Revises: 5fd9c68edeb7
Create Date: 2025-10-16 02:50:36.580130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be930e013b3a'
down_revision: Union[str, Sequence[str], None] = '5fd9c68edeb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('foo', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('bar', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_users_foo_bar'), 'users', ['foo', 'bar'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_foo_bar'), 'users', type_='unique')
    op.drop_column('users', 'bar')
    op.drop_column('users', 'foo')
    # ### end Alembic commands ###
