"""edit user and media model

Revision ID: 1dc96df8bf3a
Revises: 8960f9b977c6
Create Date: 2025-10-30 16:01:05.553257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc96df8bf3a'
down_revision: Union[str, Sequence[str], None] = '8960f9b977c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('media', 'title',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('media', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('media', 'comments_count')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.add_column('media', sa.Column('comments_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('media', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('media', 'title',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('media', 'url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
